### PR TITLE
Java12, smaller Docker image, other improvements

### PR DESCRIPTION
**Pull request by tashoyan**
1. Updated to support Java 12
   1. Now using `com.sun.activation:jakarta.activation` because javax.activation is deprecated in Java 9.
   1. Eliminated the dependency on JavaFX. JavaFX is not a part of JDK anymore. Moreover, Kafka Visualizer does not actually use JavaFX functionality.
1. Made some optimizations, for example compile a Pattern once.
1. Fixed some compiler warnings
1. Improvements in building the Docker image
   1. Made the image much smaller. Previous image contained all the data generated by all build stages - jars, Node.js modules, etc. Moreover, previous image contained build tools like Maven or npm. New image contains only the things needed for runtime: the application jar, JVM and Node.js. New image is based on the lightweight Alpine Linux distribution.
   1. Made the image build process faster. This is done by excluding irrelevant data from the build context. Now the build context has only the application jar and the Dockerfile.
   1. As a result, new image is **419 MB** instead of previous **1.69 GB**.
1. Fixed logging. Now SLF4J is used throughout the application, including Spring Boot and Kafka API. No direct calls to Log4J anymore.
1. All files generated by build are now created in `target` directories. As per Maven convention, these directories are cleaned and do not pollute the source code tree.
1. Upgraded Kafka dependency to `2.3.0`

### CODE REVIEW

**Comment by manasb-uoe** [comment]
Wow! Thanks a  lot for the contribution, I haven't had the time to maintain this project so this PR is a much appreciated. I'll have a look in a bit and merge.

**Comment by manasb-uoe** [comment]
image

The docker build seems to fail when doing a `mvn package` from the root directory. Works for you?

**Comment by manasb-uoe** [comment]
@tashoyan Tested the rest by removing the docker module from the POM, and it all seems to be working correctly. Do let me know if you're seeing the above error when packaging for the first time.

**Comment by tashoyan** [comment]
I cannot reproduce this error. My configuration:

- OpenJDK 12.0.2
- Maven 3.6.0
- Red Hat Linux 7.5

In order to reproduce the problem I made a cleanup:

```bash
mvn clean
rm -r ~/.m2/repository/com/enthusiast94/
```

Then I ran `mvn package` and the build finished without errors.

I checked the mentioned issue [MDEP-187](https://issues.apache.org/jira/browse/MDEP-187) - it refers to m2e. Are you using m2e (Eclipse Maven plugin)? Some people say that [the build may fail in Eclipse but runs ok in console](https://stackoverflow.com/questions/30642630/artifact-has-not-been-packaged-yet). If you have anything about m2e, then please try to remove it.

As the last resort, we can workaround this problem by tuning phases according to [Maven Lifecycle reference](http://maven.apache.org/ref/3.6.1/maven-core/lifecycles.html). For example:

- Copy the Dockerfile: phase `verify`
- Copy REST App: phase `verify`
- Build Docker image: phase `install`

Thus we can shift all build steps after the `package` phase.

**Comment by manasb-uoe** [comment]
@tashoyan ah right, merging now.

**Comment by tashoyan** [comment]
Great! Thanks.

**Pull request merged**
